# Generated by Django 4.2.5 on 2023-10-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_todo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='desc',
        ),
    ]
